### ISSUE TITLE
Lua-compatible symbol files

### ISSUE THREAD

**Issue by nicklausw** [freem/asm6f#10]
``reset = 0xC000
zeropage = 0x01``
For easy live variable printing in FCEUX with Lua scripts (`memory.readbyte(zeropage)`). Should be easy.

**Comment by nicklausw** [comment]
5110c529c4723469d50d50820f503d9a4084dd89 Works well.

**Comment by freem** [comment]
sweet! I didn't even remember that this use case existed.
