### ISSUE TITLE
Allow unix absolute file path

### ISSUE THREAD

**Issue by andre-paris** [freem/asm6f#18]
It's not possible to pass absolute file names (starting with '/') as arguments.
I propose this change to fix this issue:
```diff
--- asm6f.c	(revision 762c948875e7b8c478b917f88f82c8f77b2308f8)
+++ asm6f.c	(revision )
@@ -1814,7 +1814,7 @@
 	initcomments();
 	notoption=0;
 	for(i=1;i<argc;i++) {
-		if(*argv[i]=='-' || *argv[i]=='/') {
+		if(*argv[i]=='-' || (*argv[i]=='/' && strlen(argv[i]) == 2)) {
 			switch(argv[i][1]) {
 				case 'h':
 				case '?':
```

**Comment by freem** [comment]
Tested this, seems to work for me. (At least, as long as the length of each option is still one character.) 

Thanks for the fix! Committed as hash d8bdf5628f3326bb18962420575ab0ff8ee2d259
