### ISSUE TITLE
Recent release won't run: missing msys-2.0.dll

### ISSUE THREAD

**Issue by koitsu** [freem/asm6f#23]
The current binary release from March 10th 2018 (commit 762c948) does not run on Windows citing at least one missing DLL: `msys-2.0.dll`. Others experience the same problem, so it's not limited to just me: http://forums.nesdev.com/viewtopic.php?f=2&t=17945

Older 32-bit and 64-bit releases (June 24th 2015, commit 105ee3c) both run without a hitch.

**Comment by Xkeeper0** [comment]
Compiling on Ubuntu 14.04 with this appears to create an executable that doesn't require `msys-2.0.dll` (only `msvcrt.dll`, which is everywhere):

```x86_64-w64-mingw32-gcc -o asm6f.exe asm6f.c -static```

Executable: [asm6f.zip](https://github.com/freem/asm6f/files/2496731/asm6f.zip)

**Comment by freem** [comment]
A new version (with both 32 and 64-bit builds) has been uploaded to the Releases tab with a filename of "asm6f_20181019.zip". Hopefully this fixes any issues from the previous release.

**Comment by koitsu** [comment]
Confirmed both 32-bit and 64-bit binaries in asm6f_20181019.zip are working. Thanks a ton! :+1:
