### ISSUE TITLE
[REQUEST] Add support for INES 2.0 header support

### ISSUE THREAD

**Issue by TheRealHamtaro126** [freem/asm6f#4]
Hey there, Is there any way you can add INES 2.0 header support to ASM6F? This program will get better to use if so.

**Comment by nicklausw** [comment]
Same question as the original issue, should it be implemented like tepples does it? http://wiki.nesdev.com/w/index.php/NES_2.0_header_for_ca65

Or more like unofficial-magickit? (They might be the same, I don't remember).

**Comment by TheRealHamtaro126** [comment]
Hmm... the unofficial-magickit way seems easier.

**Comment by nicklausw** [comment]
Alright, I'll get on this later today.

**Comment by nicklausw** [comment]
Just realized the existing header directives don't have any numerical limits to them...this'll be fun.

**Comment by freem** [comment]
Mentioned as a part of #1; please take discussion there.
