### ISSUE TITLE
make asm6f one program

### ISSUE THREAD

**Issue by nicklausw** [freem/asm6f#7]
The build process and distribution of the program would probably work better if asm6f was one binary with instructions `UNSTABLE` and `HUNSTABLE` to enable the corresponding opcodes. The opcode reading function in the program would just search through an array of unstable (or highly so) instructions and if it's a match but the appropriate directive hasn't been called, throw an error.

I just don't think it's necessary to have three different binaries for an assembler like this.

**Comment by freem** [comment]
merged matching pull request #9
